name: app_widget_android
description: flutter app widget
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  app_widget_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: app_widget
    platforms:
      android:
        package: tech.noxasch.app_widget
        pluginClass: AppWidgetPlugin
        dartPluginClass: AppWidgetAndroid

