name: app_widget
description: Flutter plugin that provide useful app widget api and callback into flutter
version: 0.1.0
homepage: https://noxasch.tech/
repository: https://github.com/noxasch/flutter_app_widget/tree/master/app_widget
issue_tracker: https://github.com/noxasch/flutter_app_widget/issues

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  app_widget_platform_interface: ^0.1.0
  app_widget_android: ^0.1.0
  # app_widget_platform_interface: # local dev
  #   path: ../app_widget_platform_interface
  # app_widget_android: # local dev
  #   path: ../app_widget_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: app_widget_android

