name: app_widget
description: flutter app widget
version: 0.0.1
homepage: https://github.com/noxasch/flutter_app_widget/tree/master/app_widget
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  app_widget_platform_interface:
    path: ../app_widget_platform_interface
  app_widget_android:
    path: ../app_widget_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: app_widget_android

